name: Update GitHub Stats

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          username: OmAr-Kader
          card: top-langs
          output: assets/top-langs.svg
          theme: react
          count_private: true
          include_all_commits: true

      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          username: OmAr-Kader
          card: stats
          output: assets/github-stats.svg
          theme: react
          count_private: true
          include_all_commits: true

      - name: Generate Streak
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          username: OmAr-Kader
          card: streak
          output: assets/streak.svg
          theme: react
          count_private: true

      - name: Commit generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/*.svg

          git commit -m "Update GitHub stats" || exit 0

          git push
